//! Sorting algorithms — extensible registry.
//!
//! To add a new algorithm:
//!   1. Write a function with the signature:
//!      `fn my_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event))`
//!   2. Add one line to the `sort_algo!` invocation below:
//!      `sort_algo!(MyAlgo, "myalgo", "My Algorithm", my_sort, "alias1", "alias2");`
//!
//! Everything else (enum variant, clap ValueEnum, name/code/next/prev,
//! collect_events dispatch, cache filename) is generated automatically.
//!
//! The macro also registers string aliases (case/underscore/hyphen-insensitive)
//! that clap will accept — e.g. "bubblesort", "quick-sort", "heap sort".

use std::cmp::Ordering;

use clap::ValueEnum;

/// A single atomic operation performed by a sorting algorithm.
#[derive(Clone, Copy, Debug)]
pub enum Event {
    Cmp { a: usize, b: usize },
    Swap { a: usize, b: usize },
    Set { idx: usize, value: usize },
}

/// Unified signature for all sorting implementations.
///
/// `arr` is the working array (index = cell id).
/// `cmp` compares the keys of cells at indices `a` and `b`.
/// `emit` records each atomic event.
type SortFn = dyn for<'a> Fn(
    &mut [usize],
    &'a dyn Fn(usize, usize) -> Ordering,
    &mut dyn FnMut(Event),
);

/// Macro that registers a sorting algorithm.
///
/// Expands to the enum variant + metadata, and adds the entry to the
/// compile-time registry table. All derived methods (code, name, next, prev,
/// collect_events dispatch) are driven from this single table.
macro_rules! sort_algo {
    // Each invocation: (Variant, "code", "Display name", function_name, aliases...)
    ($(
        $variant:ident, $code:literal, $name:literal, $fn:ident $(, $alias:literal)* $(,)?
    );+ $(;)?) => {
        /// The sorting algorithm to visualise.
        ///
        /// Variants are generated by the `sort_algo!` macro — see its
        /// invocation at the bottom of this file. To add a new algorithm,
        /// just add one line there.
        #[derive(Clone, Copy, PartialEq, Eq, Debug, ValueEnum)]
        pub enum Algo {
            $($variant),+
        }

        /// Metadata for one algorithm.
        #[allow(dead_code)]
        struct AlgoMeta {
            variant: Algo,
            code: &'static str,
            name: &'static str,
            aliases: &'static [&'static str],
            func: &'static SortFn,
        }

        // Compile-time table — single source of truth.
        const ALGO_TABLE: &[AlgoMeta] = &[
            $(
                AlgoMeta {
                    variant: Algo::$variant,
                    code: $code,
                    name: $name,
                    aliases: &[$($alias),*],
                    func: &$fn,
                },
            )+
        ];

        impl Algo {
            /// All algorithms in registration order.
            pub const ALL: &[Algo] = &[$(Algo::$variant),+];

            /// Stable numeric code (0..) for cache filenames and headers.
            pub fn code(self) -> u8 {
                ALGO_TABLE.iter().position(|m| m.variant == self).unwrap() as u8
            }

            /// Alias for `code()` — stable numeric id for serialization.
            #[allow(dead_code)]
            pub fn id(self) -> u8 { self.code() }

            /// Human-readable display name.
            pub fn name(self) -> &'static str {
                ALGO_TABLE.iter().find(|m| m.variant == self).unwrap().name
            }

            /// Short code string for cache filenames ("bubble", "insertion", ...).
            pub fn code_str(self) -> &'static str {
                ALGO_TABLE.iter().find(|m| m.variant == self).unwrap().code
            }

            /// Next algorithm in registration order (wraps).
            pub fn next(self) -> Algo {
                let idx = ALGO_TABLE.iter().position(|m| m.variant == self).unwrap_or(0);
                ALGO_TABLE[(idx + 1) % ALGO_TABLE.len()].variant
            }

            /// Previous algorithm (wraps).
            pub fn prev(self) -> Algo {
                let idx = ALGO_TABLE.iter().position(|m| m.variant == self).unwrap_or(0);
                ALGO_TABLE[(idx + ALGO_TABLE.len() - 1) % ALGO_TABLE.len()].variant
            }

            /// Look up by numeric code (used by cache deserialization).
            pub fn from_code(code: u8) -> Option<Algo> {
                ALGO_TABLE.get(code as usize).map(|m| m.variant)
            }

            /// Look up by string code (case-insensitive, hyphen/underscore-tolerant).
            /// Used by clap's ValueEnum derive.
            pub fn from_str(s: &str, _ignore_case: bool) -> Result<Self, String> {
                let norm = s.trim().to_lowercase().replace([' ', '_', '-'], "");
                ALGO_TABLE.iter()
                    .find(|m| {
                        let code_norm = m.code.replace(['_', '-'], "");
                        if code_norm == norm { return true; }
                        m.aliases.iter().any(|a| a.replace(['_', '-'], "") == norm)
                    })
                    .map(|m| m.variant)
                    .ok_or_else(|| format!("unknown algorithm '{s}'"))
            }
        }
    };
}

/// Bubble sort.
fn bubble_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    let n = arr.len();
    for i in (1..n).rev() {
        for j in 0..i {
            emit(Event::Cmp { a: j, b: j + 1 });
            if cmp(arr[j], arr[j + 1]) == Ordering::Greater {
                arr.swap(j, j + 1);
                emit(Event::Swap { a: j, b: j + 1 });
            }
        }
    }
}

/// Insertion sort.
fn insertion_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    let n = arr.len();
    for i in 1..n {
        let mut j = i;
        while j > 0 {
            emit(Event::Cmp { a: j - 1, b: j });
            if cmp(arr[j - 1], arr[j]) == Ordering::Greater {
                arr.swap(j - 1, j);
                emit(Event::Swap { a: j - 1, b: j });
                j -= 1;
            } else {
                break;
            }
        }
    }
}

/// Selection sort.
fn selection_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    let n = arr.len();
    for i in 0..n.saturating_sub(1) {
        let mut min = i;
        for j in (i + 1)..n {
            emit(Event::Cmp { a: min, b: j });
            if cmp(arr[j], arr[min]) == Ordering::Less {
                min = j;
            }
        }
        if min != i {
            arr.swap(i, min);
            emit(Event::Swap { a: i, b: min });
        }
    }
}

/// Quicksort (Lomuto partition, recursive).
fn quick_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    fn qs(lo: usize, hi: usize, arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
        if lo >= hi { return; }
        let pivot = arr[hi];
        let mut i = lo;
        for j in lo..hi {
            emit(Event::Cmp { a: j, b: hi });
            if cmp(arr[j], pivot) == Ordering::Less {
                arr.swap(i, j);
                emit(Event::Swap { a: i, b: j });
                i += 1;
            }
        }
        if i != hi {
            arr.swap(i, hi);
            emit(Event::Swap { a: i, b: hi });
        }
        if i > lo { qs(lo, i - 1, arr, cmp, emit); }
        if i + 1 < hi { qs(i + 1, hi, arr, cmp, emit); }
    }
    let n = arr.len();
    if n > 1 { qs(0, n - 1, arr, cmp, emit); }
}

/// Heapsort (max-heap, 0-based indexing).
fn heap_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    let n = arr.len();
    if n < 2 { return; }

    // Build max-heap.
    for start in (0..n / 2).rev() {
        sift_down(arr, start, n, cmp, emit);
    }
    // Extract repeatedly.
    for end in (1..n).rev() {
        arr.swap(0, end);
        emit(Event::Swap { a: 0, b: end });
        sift_down(arr, 0, end, cmp, emit);
    }

    fn sift_down(
        arr: &mut [usize],
        mut root: usize,
        size: usize,
        cmp: &dyn Fn(usize, usize) -> Ordering,
        emit: &mut dyn FnMut(Event),
    ) {
        loop {
            let left = root * 2 + 1;
            if left >= size { break; }
            let right = left + 1;

            let mut largest = root;
            emit(Event::Cmp { a: left, b: root });
            if cmp(arr[left], arr[largest]) == Ordering::Greater {
                largest = left;
            }
            if right < size {
                emit(Event::Cmp { a: right, b: largest });
                if cmp(arr[right], arr[largest]) == Ordering::Greater {
                    largest = right;
                }
            }
            if largest == root { break; }
            arr.swap(root, largest);
            emit(Event::Swap { a: root, b: largest });
            root = largest;
        }
    }
}

/// Mergesort (top-down, auxiliary buffer, in-place copy-back).
fn merge_sort(arr: &mut [usize], cmp: &dyn Fn(usize, usize) -> Ordering, emit: &mut dyn FnMut(Event)) {
    let n = arr.len();
    if n < 2 { return; }
    let mut aux = vec![0usize; n];
    merge(arr, &mut aux, 0, n, cmp, emit);

    fn merge(
        arr: &mut [usize],
        aux: &mut [usize],
        lo: usize,
        hi: usize,
        cmp: &dyn Fn(usize, usize) -> Ordering,
        emit: &mut dyn FnMut(Event),
    ) {
        if hi - lo < 2 { return; }
        let mid = lo + (hi - lo) / 2;
        merge(arr, aux, lo, mid, cmp, emit);
        merge(arr, aux, mid, hi, cmp, emit);

        let (mut i, mut j, mut k) = (lo, mid, lo);
        while i < mid && j < hi {
            emit(Event::Cmp { a: i, b: j });
            if cmp(arr[i], arr[j]) == Ordering::Less {
                aux[k] = arr[i];
                emit(Event::Set { idx: k, value: arr[i] });
                i += 1;
            } else {
                aux[k] = arr[j];
                emit(Event::Set { idx: k, value: arr[j] });
                j += 1;
            }
            k += 1;
        }
        while i < mid {
            aux[k] = arr[i];
            emit(Event::Set { idx: k, value: arr[i] });
            i += 1;
            k += 1;
        }
        while j < hi {
            aux[k] = arr[j];
            emit(Event::Set { idx: k, value: arr[j] });
            j += 1;
            k += 1;
        }
        for (offset, &value) in aux[lo..hi].iter().enumerate() {
            let idx = lo + offset;
            arr[idx] = value;
            emit(Event::Set { idx, value });
        }
    }
}

/// Single registration point — to add an algorithm, add one line here.
/// Aliases are additional spellings accepted by clap (case/underscore/hyphen-insensitive).
sort_algo!(
    Bubble,     "bubble",     "Bubble sort",     bubble_sort,     "bubblesort";
    Insertion,  "insertion",  "Insertion sort",  insertion_sort,  "insertionsort";
    Selection,  "selection",  "Selection sort",  selection_sort,  "selectionsort";
    Quick,      "quick",      "Quicksort",       quick_sort,      "quicksort";
    Heap,       "heap",       "Heapsort",        heap_sort,       "heapsort";
    Merge,      "merge",      "Mergesort",       merge_sort,      "mergesort";
);

/// Table-driven dispatcher — call the registered function for the algorithm.
pub fn collect_events(
    algo: Algo,
    arr: &mut [usize],
    cmp: &dyn Fn(usize, usize) -> Ordering,
) -> Vec<Event> {
    let mut events = Vec::new();
    let mut emit = |e: Event| events.push(e);
    // Look up the function in the table.
    if let Some(m) = ALGO_TABLE.iter().find(|m| m.variant == algo) {
        (m.func)(arr, cmp, &mut emit);
    }
    events
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_algos_sort_and_replay() {
        for &algo in Algo::ALL {
            for n in [0usize, 1, 2, 3, 5, 17, 64, 200] {
                let mut arr: Vec<usize> = (0..n).rev().collect();
                let cmp = |a: usize, b: usize| a.cmp(&b);
                let events = collect_events(algo, &mut arr, &cmp);

                assert!(
                    arr.windows(2).all(|w| w[0] <= w[1]),
                    "{algo:?} n={n}: array not sorted"
                );

                // Replay the events over a fresh copy.
                let mut vis: Vec<usize> = (0..n).rev().collect();
                for e in &events {
                    match *e {
                        Event::Cmp { .. } => {}
                        Event::Swap { a, b } => vis.swap(a, b),
                        Event::Set { idx, value } => vis[idx] = value,
                    }
                }
                assert_eq!(vis, arr, "{algo:?} n={n}: replay diverged");
            }
        }
    }

    #[test]
    fn code_roundtrip() {
        for &algo in Algo::ALL {
            let c = algo.code();
            assert_eq!(Algo::from_code(c), Some(algo), "code {c} -> {algo:?} failed");
        }
    }

    #[test]
    fn str_lookup() {
        assert_eq!(Algo::from_str("bubble", true), Ok(Algo::Bubble));
        assert_eq!(Algo::from_str("bubblesort", true), Ok(Algo::Bubble));
        assert_eq!(Algo::from_str("QUICK", true), Ok(Algo::Quick));
        assert_eq!(Algo::from_str("quick-sort", true), Ok(Algo::Quick));
        assert_eq!(Algo::from_str("heap sort", true), Ok(Algo::Heap));
        assert_eq!(Algo::from_str("merge-sort", true), Ok(Algo::Merge));
        assert!(Algo::from_str("nope", true).is_err());
    }

    #[test]
    fn next_prev_cycle() {
        let first = Algo::ALL[0];
        let mut cur = first;
        for _ in 0..Algo::ALL.len() {
            cur = cur.next();
        }
        assert_eq!(cur, first, "next cycle broken");
        for _ in 0..Algo::ALL.len() {
            cur = cur.prev();
        }
        assert_eq!(cur, first, "prev cycle broken");
    }

    #[test]
    fn collects_events_on_reverse_input() {
        let mut arr: Vec<usize> = (0..20).rev().collect();
        let events = collect_events(Algo::Quick, &mut arr, &|a, b| a.cmp(&b));
        assert!(!events.is_empty());
    }
}